name: ntfy
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: niniyas/ntfy-action@master
        with:
          url: https://ntfy.sh
          topic: nostrich
