name: ntfy
on: push
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - run: curl -o /bin/nak https://github.com/fiatjaf/nak/releases/download/v0.7.5/nak-v0.7.5-linux-amd64
      - run: chmod +x /bin/nak
      - run: nak event -k 1 -c "nak on github actions" --sec ${{secrets.nsec}} nos.lol
