name: ntfy
on: [push]
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: blackshot/ntfy-action@master
        with:
          url: 'https://ntfy.sh'
          tags: 'test'
          topic: 'test'
          details: 'hello world'
