name: ntfy
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: robiningelbrecht/ntfy-action@v1.0.0
        with:
          url: https://ntfy.sh
          topic: nostrich
          job_status: ${{ job.status }}
