name: ntfy
on: [push]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: ntfy-push
        run: curl -s ntfy.sh/test -d "test" #"Repo: ${{ github.repository }}\nCommit: ${{ github.sha }}\nRef: ${{ github.ref }}\nStatus: ${{ job.status}}"
