name: ntfy
on: [push]
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: niniyas/ntfy-action@master
        with:
          url: 'https://ntfy.sh'
          topic: 'test'
          actions: disabled
          details: hello world
